### ISSUE TITLE
40 pin tsop

### ISSUE THREAD

**Issue by NO-ob** [JRodrigoTech/FLASH-ROM-Adapter-for-GameBoy#1]
Is it possible to use a 40 pin tsop? I ordered AM29F032B-90EI and its 40 pin

**Comment by JRodrigoTech** [comment]
Yes, you need to solder it in the middle of the footprint leaving 2 pads unused on each side.

![AM29F032B](https://user-images.githubusercontent.com/1735665/165367480-47d58b09-bb40-4a44-9c0f-f0684f44ba27.jpg)

**Comment by NO-ob** [comment]
Cool thankyou, turns out I ordered the wrong adapter anyway lol
